export { default as Home } from './Home'
export { default as MovieDetail } from './MovieDetail'
export { default as WatchMovie } from './WatchMovie'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as MovieList } from './MovieList'
